modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/MightyPirates/MarkdownManual/issues"
license = "MIT"

[[mods]]
modId = "markdown_manual"
version = "${file.jarVersion}"
displayName = "Markdown Manual"
authors = "Sangar"
description = '''
Library mod providing a convenient way of defining in-game manuals.
'''

[[dependencies.markdown_manual]]
modId = "forge"
mandatory = true
versionRange = "[36.1.32,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.markdown_manual]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
