name: publish

on:
  release:
    types: [published]

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract Version from Tag
        uses: rishabhgupta/split-by@v1
        id: split_tag
        with:
          string: ${{ github.event.release.tag_name }}
          split-by: '/'

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ubuntu-latest-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ubuntu-latest-gradle-
      - name: Build with Gradle
        run: ./gradlew -Psemver='${{ steps.split_tag.outputs._1 }}' build

      - name: Add Artifacts to Github Release
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/libs/*.jar"]'

      - name: Publish to Github Packages
        run: gradle -Psemver='${{ steps.split_tag.outputs._1 }}' publish
        env:
          GITHUB_MAVEN_URL: 'https://maven.pkg.github.com/${{ github.repository }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Curseforge
        run: ./gradlew -Psemver='${{ steps.split_tag.outputs._1 }}' curseforge
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          CHANGELOG: ${{ github.event.release.body }}
