name: publish

on:
  push:
    tags:
      - '*/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: rishabhgupta/split-by@v1
        id: split_tag
        with:
          string: ${{ github.ref }}
          split-by: '/'

      - name: Bump Version
        run: sed -i 's/semver=0.0.0/semver=${{ steps.split_tag.outputs._2 }}/g' gradle.properties

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x gradlew
      - run: ./gradlew build

      - name: Publish to Github
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.md
          files: ./build/libs/*.jar
          name: ${{ steps.split_tag.outputs._2 }} (MC${{ steps.split_tag.outputs._1 }})

#      - name: Publish to Maven
#        run: ./gradlew publish
#
#      - name: Publish to Curseforge
#        run: ./gradlew curseforge
